### ISSUE TITLE
Low resolution images loaded

### ISSUE THREAD

**Issue by arthurrasmusson** [Shinsi2/Shinsi2#11]
Some images appear to load the low resolution version of the original image in a gallery. Images affected by this bug remain low resolution while others load properly later on in the gallery. This behaviour is seemingly random as I’ve noticed no pattern the occurrence of this issue other than that it generally only affects a few images per gallery.

**Comment by Shinsi2** [comment]
Ya, It's a know bug. Properly a thread bug (or just a network problem). 
It's happen randomly so really hard to debug.
Just close the viewer and touch thumbnail again will solve the problem sometimes.

**Comment by arthurrasmusson** [comment]
Is there some way to detect the issue and re-initiate the image loading function? Perhaps after a certain timeout period?

**Comment by Shinsi2** [comment]
You can look into
https://github.com/Shinsi2/Shinsi2/blob/8eccbbc98b411a3abef5e3c39f869cf713f7ee62/Shinsi2/Model/SSPhoto.swift#L24

The process is to get the HTML first and then parse and get the URL of the image.
An error may have occurred in obtaining the HTML.
There's no retry. So it stop here.

**Comment by Shinsi2** [comment]
https://github.com/Shinsi2/Shinsi2/blob/6200a0f6dbf08f9fd3a1687603048c2e43e1b106/Shinsi2/ViewControllers/ViewerVC.swift#L268

I found the bug, I will fix it later.
Problem is the cell trying to reload is not in the `collectionView.indexPathsForVisibleItems`

**Comment by arthurrasmusson** [comment]
Great stuff. Thanks for looking into this. I can't wait for the fix to get pushed.

**Comment by Shinsi2** [comment]
Already merged.

**Comment by arthurrasmusson** [comment]
I've compiled the latest version and tested it. The issue still appears to occur.

**Comment by Shinsi2** [comment]
Do you try scroll to next 3~4 pages then scroll back.
Is it still blur? Maybe it's really a network problem.
Please try logging for every pages here.
https://github.com/Shinsi2/Shinsi2/blob/9be50d94d6e71907808b1d66dfe961600214e644/Shinsi2/Model/SSPhoto.swift#L30-L37
