### ISSUE TITLE
希望可以自动保存本子查看的进度

### ISSUE THREAD

**Issue by liyiecho** [Shinsi2/Shinsi2#7]
有时候本子页数比较多，一下子看不完，退出后，又要重新开始，希望可以退出本子后自动保存进度，这样下次查看的时候，可以选择重新查看或者从最后查看的进度开始查看。

**Comment by Shinsi2** [comment]
有時間的話會考慮

**Comment by Shinsi2** [comment]
https://app.bitrise.io/artifact/36625829/p/6b94cbe2552c7c5e418c0605ec7ad5cb
